# tasks/configure_firewall.yml

# Red Hat Systems
- name: Configure firewall
  block:
    - name: Install firewalld (Red Hat)
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Start and enable firewalld (Red Hat)
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open port for Jenkins in firewalld (Red Hat)
      ansible.builtin.firewalld:
        port: "{{ jenkins_http_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
  when: ansible_os_family == 'RedHat'

# Ubuntu/Debian Systems
- name: Configure firewall
  block:
    - name: Install UFW (Ubuntu/Debian)
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow Jenkins port in UFW (Ubuntu/Debian)
      community.general.ufw:
        rule: allow
        port: "{{ jenkins_http_port }}"
        proto: tcp

    - name: Allow SSH in UFW (Ubuntu/Debian)
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW (Ubuntu/Debian)
      community.general.ufw:
        state: enabled
  when: ansible_os_family == 'Debian'
