# tasks/install_dependencies.yml

- name: Update package index (Ubuntu/Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install required packages (Ubuntu/Debian)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == 'Debian'

- name: Install required packages (Red Hat)
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - ca-certificates
      - curl
    state: present
  when: ansible_os_family == 'RedHat'
