# tasks/selinux.yml

- name: Check SELinux status
  ansible.builtin.command: getenforce
  register: selinux_status

- name: Set SELinux to permissive mode
  ansible.builtin.command: setenforce 0
  when: selinux_status.stdout == "Enforcing"

- name: Modify SELinux config file to set permissive mode on reboot
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  when: selinux_status.stdout == "Enforcing"
