name: Release Role

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible Galaxy CLI
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Publish to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
        run: |
          ansible-galaxy role import mamrezb jenkinsmaster-ansible-role --token $ANSIBLE_GALAXY_TOKEN
